name: Trace GitHub Actions Workflows

on:
  workflow_run:
    workflows:
      - "Alternative CI Runners 5"
    types:
      - completed

permissions:
  contents: read

jobs:
  run:
    name: Export '${{ github.event_name }}' workflow trace
    runs-on: ubuntu-latest
    # TODO: 👇 Change this to match your fork name
    if: ${{ github.repository == 'dagger/dagger' }}
    steps:
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: grpc://api.honeycomb.io:443/
          otlpHeaders: ${{ secrets.HONEYCOMB_GITHUB_ACTIONS_WORKFLOWS }}
          otelServiceName: dagger-dagger-github-actions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
